# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Stéphane Faucher"
resume_title:                   "Développeur"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "stephane.faucher@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "514-918-9270"
resume_contact_address:         "Laval, Québec"

resume_header_contact_info:     "Laval, Québec • 514-918-9270 • stephane.faucher@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>Je me considère comme une personne dynamique, capable d'initiative et de débrouillardise. Je suis à l'écoute de mes clients pour qui je vise la satisfaction par une garantie de résultat.</p><p>Je suis capable d'avoir une vue d'ensemble des projets qui me sont confiés et je peux atteindre rapidement les objectifs fixés. Je suis pro-actif dans ma réponse au client en offrant suggestions et propositions en vue d'améliorer constamment le produit recherché.</p><p>Je suis une personne autonome qui requiert peu de supervision. Je possède un bon esprit d'analyse, je suis créatif et bon communicateur. Je vise l'excellence dans les projets dont j'ai la charge parce que j'aime relever des défis stimulants et réussir ce que j'entreprends.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/sfauch1"
  resume_twitter_url:           "https://twitter.com/stephanefaucher"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/stephanefaucher/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
